const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.JavaScriptInEvents.Folhafase1_Event21_Act1,
		C3.Plugins.Mouse.Cnds.OnAnyClick
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Piso1: 0},
	{Piso2: 0},
	{Piso3: 0},
	{Ilha1: 0},
	{Ilha2: 0},
	{Ilha3: 0},
	{Fundo: 0},
	{Fragmento: 0},
	{Lava1: 0},
	{Fundo2: 0},
	{Piso4: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Indicativo: 0},
	{Tocha1: 0},
	{Cogumelo1: 0},
	{Ponte1: 0},
	{Ponte2: 0},
	{Ponte3: 0},
	{TextoFragmentos: 0},
	{Mouse: 0},
	{FundoMenu: 0},
	{BotãoJogar: 0},
	{Parede: 0},
	{Ponta1: 0},
	{Chão: 0},
	{Porta: 0},
	{Indicativo2: 0},
	{Bau: 0},
	{Porta2: 0},
	{TelaFimDeJogo: 0},
	{TelaGameOver: 0},
	{BotãoContinuar: 0},
	{Áudio: 0},
	{TextoObjetivo: 0},
	{Espinho: 0},
	{Fragmentos: 0}
];

self.InstanceType = {
	Piso1: class extends self.ISpriteInstance {},
	Piso2: class extends self.ISpriteInstance {},
	Piso3: class extends self.ISpriteInstance {},
	Ilha1: class extends self.ISpriteInstance {},
	Ilha2: class extends self.ISpriteInstance {},
	Ilha3: class extends self.ISpriteInstance {},
	Fundo: class extends self.ISpriteInstance {},
	Fragmento: class extends self.ISpriteInstance {},
	Lava1: class extends self.ISpriteInstance {},
	Fundo2: class extends self.ISpriteInstance {},
	Piso4: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Indicativo: class extends self.ISpriteInstance {},
	Tocha1: class extends self.ISpriteInstance {},
	Cogumelo1: class extends self.ISpriteInstance {},
	Ponte1: class extends self.ISpriteInstance {},
	Ponte2: class extends self.ISpriteInstance {},
	Ponte3: class extends self.ISpriteInstance {},
	TextoFragmentos: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	FundoMenu: class extends self.ISpriteInstance {},
	BotãoJogar: class extends self.ISpriteInstance {},
	Parede: class extends self.ISpriteInstance {},
	Ponta1: class extends self.ISpriteInstance {},
	Chão: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Plataforma: class extends self.ISpriteInstance {},
	Indicativo2: class extends self.ISpriteInstance {},
	Bau: class extends self.ISpriteInstance {},
	Porta2: class extends self.ISpriteInstance {},
	TelaFimDeJogo: class extends self.ISpriteInstance {},
	TelaGameOver: class extends self.ISpriteInstance {},
	BotãoContinuar: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	TextoObjetivo: class extends self.ITextInstance {},
	Espinho: class extends self.ISpriteInstance {}
}